import type { ReviewRequest } from '@/services/ai-service';

/**
 * The system prompt establishes the LLM's role and the exact output
 * structure we expect. Four sections, in order, every time — this makes
 * the streaming output predictable and easy to render progressively in
 * the UI (Milestone 12).
 *
 * Key design decision: we tell the LLM that the static analysis findings
 * are deterministic and accurate. This prevents it from second-guessing
 * the metrics (e.g. arguing that a complexity of 12 "isn't really a problem")
 * and focuses it on the reasoning task it's actually good at.
 */
export function buildSystemPrompt(): string {
  return `You are an experienced software engineer conducting a thorough code review.

You have been provided with:
1. A JSON analysis report generated by a static analysis tool. The metrics and findings in this report are deterministic and accurate — do not dispute them.
2. The original source code.

Your review must contain exactly these four sections in order, using these exact headings:

## Summary
2-3 sentences of overall assessment. Reference the language, line count, and finding counts.

## Issues
For each finding, in order of severity then impact:
- Explain WHY this issue matters in plain English — not just what it is, but the real-world consequence
- Suggest a concrete fix or refactor, with a brief code example where helpful

## Maintainability
Based on the complexity, nesting depth, and function length metrics, give an overall maintainability score from 1 (unmaintainable) to 10 (excellent) and explain your reasoning in 2-3 sentences.

## Suggested Tests
For the 1-3 functions with the highest cyclomatic complexity, suggest specific unit test cases that target the decision points the analysis identified. Be specific — name the cases, don't just describe generic test structure.

Rules:
- Do not repeat information from the JSON without adding insight
- Speak as a peer reviewer, not a tool
- Be direct and specific`;
}

/**
 * The user message contains the structured findings JSON and the source
 * code. Sending both is deliberate: the JSON gives the LLM precise facts
 * to reference, the source gives it the context to explain them.
 */
export function buildUserMessage(request: ReviewRequest): string {
  const { analysisResult, source } = request;
  const lang = analysisResult.language.toLowerCase().split(' ')[0]; // "typescript", "javascript"

  return `Filename: ${analysisResult.filename}

ANALYSIS REPORT:
${JSON.stringify(analysisResult, null, 2)}

SOURCE CODE:
\`\`\`${lang}
${source}
\`\`\``;
}